syntax = "proto3";

package cif.channelcore;

service ChannelCore {
  rpc GetChannels (Empty) returns (Channels) {}
  rpc SetConnection (ConnectSubscriber) returns (Status) {}
  rpc SetForce (ForceChannel) returns (Status) {} //This is only supported on tags.
  rpc CreateFIFOInstance (FIFOInstance) returns (FIFOReference) {}  //FIFOs can are 1-1 connections.  To support multiple subscribers
    // when conncting to a FIFO you must first request the publisher create a specific instance for this connection.
  rpc DestroyFIFOInstance (FIFOReference) returns (Status) {} //Destroy the specific FIFO instance for a subsciber.  
}

enum Direction {
  PUBLISHER = 0;
  SUBSCRIBER = 1;
}

message Channel {
  string name = 1;
  Direction direction = 2;
  string type = 3;  //This field describes the channel type.  From LabVIEW it is typically the name of the channel class.
  bytes custom_config = 4;  //This field allows passing free form custom data needed to describe the channel and to support operations such as creating connections.  It's implementation will be type specific. 
  bool connected = 5;
  string connected_name = 6;  //This is only valid for subscribers.  Publishers typically have no knowledge of connections.  
  bool forced = 7; //Indicates if the value is being "forced" to always return a specific override value.  
}

message Channels {
  repeated Channel channels = 1;
}

message ConnectSubscriber {
  string subscriber_name = 1;
  string publisher_name = 2;
  bytes custom_connect = 3;  //This field allows passing free form custom data needed to perform specific connection operations.  It's implementation will be type specific.  
}

message FIFOInstance {
  string publisher_name = 1; //The name of the existing FIFO to create a new instance for the subscriber
  bool retry_on_timeout = 2; //Is the subscriber applying backpressure to control the rate of the publisher.  On FIFO full (timeout) the publisher will retry until space is available.
    //This is normally only used for file read publishers.  This value is applied as an AND with the publisher configuration (will only apply backpressure if publisher is configured for backpressure support).
  bool primary_subscriber = 3;  //Only the primary subsciber will support timeout.  There can only be a single primary subscriber.  
    //By default the first subscriber will be the primary unless another subscriber sets this flag true.  Then the new subscriber will be the primary.
  uint32 message_per_fifo_override = 4;  //A value of 0 indicates don't override.  This is the number of "elements" in the FIFO buffer.  
    //"Element" definition is implementation specific.  Typically this is bytes to support variable length payloads but when payload size is fixed it may be a full payload messages.
}

message FIFOReference {
  string publisher_instance_name = 1; //Unique instance of the FIFO publisher name.
}

message ForceChannel {
  string channel_name = 1;
  bool force = 2;
  bytes force_data = 3;  //Flattened data for the forced value.  Values are big endian.  
}

message Status {
   int32 code = 1;
   string message = 2;
}

message Empty {}